version: "2"
services:

  fluentd:
    image: ppcelery/fluentd-docker-image
    restart: always
    networks:
      - fluentd
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: fluentd
    volumes:
      - /fluent.conf:/etc/fluentd/fluent.conf
    ports:
      - 24225:24225
      - 24326:24326

networks:
  fluentd:
    driver: bridge
